### ISSUE TITLE
Allow user to remove kyzer modifications, and revert back to upstream builds

### ISSUE THREAD

**Issue by Frontear** [Kontort/OsuKyzer#1]
This can be a toggle in-game. The reason is that I want to be able to inject kyzer modifications into the official client without requiring this client. Regardless, isn't a priority, and is subject to change.

**Comment by Kontorted** [comment]
This is a bad idea. I am sure peppy won't appreciate us trying to inject the official client full of crap, it might lead to someone getting restricted.

**Comment by Frontear** [comment]
SPAM!?
